# ==========================================
# Docker Compose Override - Desarrollo Local
# ==========================================
# Este archivo se usa automáticamente para desarrollo local
# Sobrescribe configuraciones del docker-compose.yml principal

services:
  # Configuración de desarrollo para Kedro
  kedro-prod:
    profiles:
      - development
    environment:
      - KEDRO_ENV=local
    command: ["kedro", "viz", "run", "--host", "0.0.0.0", "--port", "4141"]
    
  # JupyterLab siempre disponible en desarrollo
  jupyter-lab:
    profiles:
      - development
    environment:
      - KEDRO_ENV=local
    volumes:
      - ./proyecto-ml:/app  # Montar todo el proyecto para hot-reload
    
  # Redis siempre disponible en desarrollo
  redis:
    profiles:
      - development
      
  # PostgreSQL opcional en desarrollo
  postgres:
    profiles:
      - development
      - database
    environment:
      - POSTGRES_DB=rainbow_six_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev123
      
  # MLflow para experimentos locales
  mlflow:
    profiles:
      - development