# DVC Pipeline Configuration
# This file defines the data science pipeline stages with DVC for versioning
# data, features, models, and metrics as required by the evaluation criteria.

stages:
  # Stage 1: Data preparation and cleaning
  data_preparation:
    cmd: kedro run --pipeline=rainbow_six
    deps:
    - data/01_raw/datadump_s5-000.csv
    - data/01_raw/datadump_s5-001.csv  
    - data/01_raw/datadump_s5-002.csv
    - src/proteyecto_ml/pipelines/rainbow_six
    outs:
    - data/02_intermediate/combined_raw.csv
    - data/02_intermediate/clean_data.csv
    - data/02_intermediate/data_sin_atipicos.csv
    - data/02_intermediate/data_preparado.csv
    - data/02_intermediate/data_kdr.csv
    - data/02_intermediate/data_final.csv
    metrics:
    - data/08_reporting/data_quality_metrics.json
    plots:
    - data/08_reporting/data_exploration_plots.png

  # Stage 2: Classification models training
  train_classification_models:
    cmd: kedro run --pipeline=modelo_clasificacion
    deps:
    - data/02_intermediate/data_final.csv
    - src/proteyecto_ml/pipelines/modelo_clasificacion
    outs:
    - data/06_models/classification/logistic_regression.pkl
    - data/06_models/classification/knn_classifier.pkl
    - data/06_models/classification/svm_classifier.pkl
    - data/06_models/classification/decision_tree_classifier.pkl
    - data/06_models/classification/random_forest_classifier.pkl
    metrics:
    - data/06_models/classification/logistic_metrics.json
    - data/06_models/classification/knn_metrics.json
    - data/06_models/classification/svm_metrics.json
    - data/06_models/classification/dt_clf_metrics.json
    - data/06_models/classification/rf_clf_metrics.json

  # Stage 3: Regression models training  
  train_regression_models:
    cmd: kedro run --pipeline=modelo_regresion
    deps:
    - data/02_intermediate/data_final.csv
    - src/proteyecto_ml/pipelines/modelo_regresion
    outs:
    - data/06_models/regression/linear_model.pkl
    - data/06_models/regression/dt_model.pkl
    - data/06_models/regression/rf_model.pkl
    - data/06_models/regression/xgb_model.pkl
    - data/06_models/regression/svr_model.pkl
    metrics:
    - data/06_models/regression/linear_metrics.json
    - data/06_models/regression/dt_metrics.json
    - data/06_models/regression/rf_metrics.json
    - data/06_models/regression/xgb_metrics.json
    - data/06_models/regression/svr_metrics.json

  # Stage 4: Model comparison and evaluation
  model_comparison:
    cmd: kedro run --pipeline=model_comparison
    deps:
    - data/06_models/classification/logistic_metrics.json
    - data/06_models/classification/knn_metrics.json
    - data/06_models/classification/svm_metrics.json
    - data/06_models/classification/dt_clf_metrics.json
    - data/06_models/classification/rf_clf_metrics.json
    - data/06_models/regression/linear_metrics.json
    - data/06_models/regression/dt_metrics.json
    - data/06_models/regression/rf_metrics.json
    - data/06_models/regression/xgb_metrics.json
    - data/06_models/regression/svr_metrics.json
    - src/proteyecto_ml/pipelines/model_comparison
    outs:
    - data/08_reporting/classification_consolidated_results.json
    - data/08_reporting/regression_consolidated_results.json
    - data/08_reporting/model_comparison.json
    plots:
    - data/08_reporting/classification_comparison.png
    - data/08_reporting/regression_comparison.png
    metrics:
    - data/08_reporting/model_comparison.json

  # Stage 5: Complete pipeline execution
  full_pipeline:
    cmd: kedro run
    deps:
    - data/01_raw/
    - src/proteyecto_ml/
    - conf/
    outs:
    - data/06_models/
    - data/08_reporting/
    metrics:
    - data/08_reporting/model_comparison.json

# DVC configuration for metrics tracking
metrics:
- data/08_reporting/model_comparison.json
- data/06_models/classification/logistic_metrics.json
- data/06_models/classification/knn_metrics.json
- data/06_models/classification/svm_metrics.json
- data/06_models/classification/dt_clf_metrics.json
- data/06_models/classification/rf_clf_metrics.json
- data/06_models/regression/linear_metrics.json
- data/06_models/regression/dt_metrics.json
- data/06_models/regression/rf_metrics.json
- data/06_models/regression/xgb_metrics.json
- data/06_models/regression/svr_metrics.json

# DVC configuration for plots tracking
plots:
- data/08_reporting/classification_comparison.png
- data/08_reporting/regression_comparison.png
- data/08_reporting/data_exploration_plots.png

# DVC configuration for model artifacts
artifacts:
  models:
    path: data/06_models/
    desc: "Trained machine learning models with hyperparameter tuning"
  data:
    path: data/02_intermediate/
    desc: "Processed and cleaned datasets ready for modeling"
  reports:
    path: data/08_reporting/
    desc: "Model evaluation reports and visualizations"