# yaml-language-server: $schema=../.vscode/schemas/dvc.schema.json
# ============================================================
# DVC Pipeline Configuration
# Optimized for Kedro project: Rainbow Six ML
# Tracks data, features, models, metrics, and reports
# ============================================================

stages:
  # Stage 1: Data Preparation & Cleaning
  data_preparation:
    cmd: kedro run --pipeline=rainbow_six
    deps:
      - data/01_raw/
      - src/proteyecto_ml/pipelines/rainbow_six
      - conf/base/parameters.yml
    outs:
      - data/02_intermediate/combined_raw.csv
      - data/02_intermediate/clean_data.csv
      - data/02_intermediate/data_sin_atipicos.csv
      - data/02_intermediate/data_preparado.csv
      - data/02_intermediate/data_kdr.csv
      - data/02_intermediate/data_final.csv
    
  
  # Stage 2: Classification Models Training
  train_classification_models:
    cmd: kedro run --pipeline=modelo_clasificacion
    deps:
      - data/02_intermediate/data_final.csv
      - src/proteyecto_ml/pipelines/modelo_clasificacion
      - conf/base/parameters.yml
    outs:
      - data/06_models/classification/

  # Stage 3: Regression Models Training
  train_regression_models:
    cmd: kedro run --pipeline=modelo_regresion
    deps:
      - data/02_intermediate/data_final.csv
      - src/proteyecto_ml/pipelines/modelo_regresion
      - conf/base/parameters.yml
    outs:
      - data/06_models/regression/

  # Stage 4: Model Comparison & Evaluation
  model_comparison:
    cmd: kedro run --pipeline=model_comparison
    deps:
      
      - src/proteyecto_ml/pipelines/model_comparison
    outs:
      - data/08_reporting/classification_consolidated_results.json
      - data/08_reporting/regression_consolidated_results.json
      - data/08_reporting/model_comparison.json

  # Stage 5: Unsupervised Learning Pipeline
  unsupervised_learning:
    cmd: kedro run --pipeline=unsupervised_learning
    deps:
      - data/02_intermediate/data_final.csv
      - conf/base/parameters.yml
    outs:
      - data/04_feature/preprocessed_data.csv
      - data/04_feature/pca_data.csv
      - data/04_feature/dbscan_result.csv
      - data/04_feature/kmeans_result.csv
      - data/04_feature/hierarchical_result.csv
    metrics:
      - data/08_reporting/clustering_metrics.json

  # Stage 6: Full Pipeline Execution
  full_pipeline:
    cmd: kedro run
    deps:
      - data/01_raw/
      - src/proteyecto_ml/
      - conf/
    # Aggregator stage without direct outs to avoid overlaps with other stages

# ============================================================
# Global DVC Configuration
# ============================================================

# Track key metrics for all experiments
metrics:
  - data/08_reporting/model_comparison.json
  - data/06_models/classification/logistic_metrics.json
  - data/06_models/classification/knn_metrics.json
  - data/06_models/classification/svm_metrics.json
  - data/06_models/classification/dt_clf_metrics.json
  - data/06_models/classification/rf_clf_metrics.json
  - data/06_models/regression/linear_metrics.json
  - data/06_models/regression/dt_metrics.json
  - data/06_models/regression/rf_metrics.json
  - data/06_models/regression/xgb_metrics.json

# Track generated plots for visual analysis
plots:
  - data/08_reporting/classification_comparison.png
  - data/08_reporting/regression_comparison.png
    # - data/08_reporting/data_exploration_plots.png

# Define tracked artifacts for versioning
artifacts:
  models:
    path: data/06_models/
    desc: "Trained machine learning models (classification & regression)"
  data:
    path: data/02_intermediate/
    desc: "Processed datasets prepared for modeling"
  reports:
    path: data/08_reporting/
    desc: "Evaluation reports, metrics, and visual comparisons"

# Optional: Include pipeline parameters
params:
  - conf/base/parameters.yml
